development:
  adapter: postgresql
  encoding: unicode
  database: hearthwiz_dev
  pool: 5
  username: tester
  password: test
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: hearthwiz_test
  pool: 5
  username: tester
  password: test
  host: localhost

development:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev