require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CardSetsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # CardSet. As you add validations to CardSet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CardSetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all card_sets as @card_sets" do
      card_set = CardSet.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:card_sets)).to eq([card_set])
    end
  end

  describe "GET #show" do
    it "assigns the requested card_set as @card_set" do
      card_set = CardSet.create! valid_attributes
      get :show, {:id => card_set.to_param}, valid_session
      expect(assigns(:card_set)).to eq(card_set)
    end
  end

  describe "GET #new" do
    it "assigns a new card_set as @card_set" do
      get :new, {}, valid_session
      expect(assigns(:card_set)).to be_a_new(CardSet)
    end
  end

  describe "GET #edit" do
    it "assigns the requested card_set as @card_set" do
      card_set = CardSet.create! valid_attributes
      get :edit, {:id => card_set.to_param}, valid_session
      expect(assigns(:card_set)).to eq(card_set)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new CardSet" do
        expect {
          post :create, {:card_set => valid_attributes}, valid_session
        }.to change(CardSet, :count).by(1)
      end

      it "assigns a newly created card_set as @card_set" do
        post :create, {:card_set => valid_attributes}, valid_session
        expect(assigns(:card_set)).to be_a(CardSet)
        expect(assigns(:card_set)).to be_persisted
      end

      it "redirects to the created card_set" do
        post :create, {:card_set => valid_attributes}, valid_session
        expect(response).to redirect_to(CardSet.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved card_set as @card_set" do
        post :create, {:card_set => invalid_attributes}, valid_session
        expect(assigns(:card_set)).to be_a_new(CardSet)
      end

      it "re-renders the 'new' template" do
        post :create, {:card_set => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested card_set" do
        card_set = CardSet.create! valid_attributes
        put :update, {:id => card_set.to_param, :card_set => new_attributes}, valid_session
        card_set.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested card_set as @card_set" do
        card_set = CardSet.create! valid_attributes
        put :update, {:id => card_set.to_param, :card_set => valid_attributes}, valid_session
        expect(assigns(:card_set)).to eq(card_set)
      end

      it "redirects to the card_set" do
        card_set = CardSet.create! valid_attributes
        put :update, {:id => card_set.to_param, :card_set => valid_attributes}, valid_session
        expect(response).to redirect_to(card_set)
      end
    end

    context "with invalid params" do
      it "assigns the card_set as @card_set" do
        card_set = CardSet.create! valid_attributes
        put :update, {:id => card_set.to_param, :card_set => invalid_attributes}, valid_session
        expect(assigns(:card_set)).to eq(card_set)
      end

      it "re-renders the 'edit' template" do
        card_set = CardSet.create! valid_attributes
        put :update, {:id => card_set.to_param, :card_set => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested card_set" do
      card_set = CardSet.create! valid_attributes
      expect {
        delete :destroy, {:id => card_set.to_param}, valid_session
      }.to change(CardSet, :count).by(-1)
    end

    it "redirects to the card_sets list" do
      card_set = CardSet.create! valid_attributes
      delete :destroy, {:id => card_set.to_param}, valid_session
      expect(response).to redirect_to(card_sets_url)
    end
  end

end
